#!/bin/bash

# Part of GPProfiles
# dot-shell_rc_alias
# ORIGIN: date unknown by hmr

echo "Processing dot-shell_rc_alias"
echo -n "  "
#
function exist_and_read() {
  local _arg1=$1
  [ -z "${_arg1}" ] && return 2
  if [ -r "${_arg1}" ]; then
    source "${_arg1}"
    return
  else
    return 1
  fi
}

# Aliases for grc
case "$(chkshell)" in
  bash )
    _FILE="/usr/local/etc/grc.bashrc"; exist_and_read "$_FILE" && echo -n "$(basename "$_FILE")" \
      || _FILE="/usr/etc/grc.bashrc" ; exist_and_read "$_FILE" && echo -n "$(basename "$_FILE")" \
      || _FILE="/etc/grc.bashrc"     ; exist_and_read "$_FILE" && echo -n "$(basename "$_FILE")"
    ;;

  zsh )
    _FILE="/usr/local/etc/grc.zsh"; exist_and_read "$_FILE" && echo -n "$(basename "$_FILE")" \
      || _FILE="/usr/etc/grc.zsh" ; exist_and_read "$_FILE" && echo -n "$(basename "$_FILE")" \
      || _FILE="/etc/grc.zsh"     ; exist_and_read "$_FILE" && echo -n "$(basename "$_FILE")"
    ;;

  fish )
    _FILE="/usr/local/etc/grc.fish"; exist_and_read "$_FILE" && echo -n "$(basename "$_FILE")" \
      || _FILE="/usr/etc/grc.fish" ; exist_and_read "$_FILE" && echo -n "$(basename "$_FILE")" \
      || _FILE="/etc/grc.fish"     ; exist_and_read "$_FILE" && echo -n "$(basename "$_FILE")"
    ;;
esac

# Don't correct spelling
case "$(chkshell)" in
  zsh )
    echo -n ", zsh-nocorrect"
    alias ssh='nocorrect ssh -A'
    alias npm='nocorrect npm'
    alias mv='nocorrect mv'
    alias cp='nocorrect cp'
    alias mkdir='nocorrect mkdir'
    ;;
esac

echo -n "ls"
alias ls='ls -CF --color=auto'                # color ls
alias ll='ls -l'                              # long list
alias la='ls -A'                              # all but . and ..
alias l='ls -CF'                              # MS-DOS Style
alias lla='ls -lA'                            # long list
alias lh='ls -lrth'                           # Human-readable special
alias lha='ls -lrthA'                         # Human-readable special

echo -n ", ssh"
alias ssh='ssh -A'                            # SSH always try to use ssh-agent.
echo -n ", sudo"
alias sudo='sudo -E'                          # sudo always preserves envs.

echo -n ", apt"
alias apt='sudo apt'                          # APT is always with sudo(for Debian/Ubuntu)

#echo -n ", grep"
#alias grep='grep --color=always'              # grep always outputs color

#alias isodate="date --iso-8601=seconds | sed -e 's/\+00:00/Z/' -e 's/[-:]//g'"
#alias utcisodate="date --utc --iso-8601=seconds | sed -e 's/\+00:00/Z/' -e 's/[-:]//g'"

echo -n ", isodate"
alias utcisodate_short=" date --utc +'%Y%m%dT%H%M%SZ'"
alias utcisodate_long="date --utc +'%Y-%m-%dT%H:%M:%SZ'"
alias utcisodate_longp="date --utc +'%Y-%m-%dT%H%M%SZ'"
alias isodate_short="date +'%Y%m%dT%H%M%S%z'"
alias isodate_long="date +'%Y-%m-%dT%H:%M:%S%z'"
alias isodate_longp="date +'%Y-%m-%dT%H%M%S%z'"

# Quilt(Tool to manage series of patches)
if which quilt > /dev/null; then
  echo -n ", quilt"
  alias dquilt="quilt --quiltrc=${XDG_CONFIG_HOME:-${HOME}}/quilt/dpkg.quiltrc"
  [ "$(chkshell)" = "bash" ] && complete -F _quilt_completion -o filenames dquilt
fi

# mtr
if which mtr > /dev/null; then
  echo -n ", mtr"
  alias mtr="sudo mtr -t -y0 -e -b"
fi

# APT
if which apt > /dev/null; then
  echo -n ", apt"
  alias as="apt search"
  alias ai="apt show"
  alias aI="apt install"
  if which apt-file > /dev/null; then
    echo -n ", apt-file"
    alias afl="apt-file list"
    alias afs="apt-file search"
  fi
fi

# BREW
if which brew > /dev/null; then
  echo -n ", brew"
  alias bs="brew search"
  alias bi="brew info"
  alias bI="brew install"
fi

# Use bat instead of less
if which bat > /dev/null; then
  echo -n ", bat"
  alias less="bat"
fi

# ffmpeg/ffplay/ffprobe
if which ffmpeg > /dev/null; then
  echo -n ", ffmpeg"
  alias ffmpeg="ffmpeg -hide_banner"
fi
if which ffplay > /dev/null; then
  echo -n ", ffplay"
  alias ffplay="ffplay -hide_banner -autoexit"
fi
if which ffprobe > /dev/null; then
  echo -n ", ffprobe"
  alias ffprobe="ffprobe -hide_banner"
fi

# Colorlized ip
if which ip > /dev/null; then
  echo -n ", ip"
  alias ip="ip -c"
fi

echo
# vim: ft=sh ts=2 sw=2 et fenc=utf-8 ff=unix
