#!/bin/bash
# vim: ft=sh ts=2 sw=2 et fenc=utf-8 ff=unix

# dot-shell_rc_misc
# ORIGIN: 2019-05-24 by hmr


echo "Processing ${UNDERLINE}${GREEN}dot-shell_rc_misc${NORMAL}"

echo -n "  Setting "
case "$(chkshell)" in
  bash )
    # Enable bash-completion
    if [ -r "/usr/local/etc/profile.d/bash_completion.sh" ]; then
      echo -n "bash-completion, "
      . "/usr/local/etc/profile.d/bash_completion.sh"
    fi
    # Set bash shell options
    TEMP_BASH_OPT="cdable_vars autocd cdspell checkhash checkjobs direxpand dirspell globstar lithist histappend "
    echo -n "bash shopts, "
    # echo "    ${TEMP_BASH_OPT}"
    shopt -s "${TEMP_BASH_OPT}"
    ;;
esac

# dircolors
if ! which dircolors >& /dev/null; then
  if [ -x "/usr/local/opt/coreutils/libexec/gnubin/dircolors" ]; then
    _TMP_DIRCOLORS_BIN="/usr/local/opt/coreutils/libexec/gnubin/dircolors"
  fi
else
  _TMP_DIRCOLORS_BIN="$(which dircolors)"
fi
if [[ -n ${_TMP_DIRCOLORS_BIN} ]]; then
  echo -n "dircolors, "
  eval "$("${_TMP_DIRCOLORS_BIN}" "${XDG_CONFIG_HOME}/dircolors/dircolors.conf")"
fi

# jEnv(Java environment switcher)
# Beware that JENV_ROOT has been defined.
if which jenv >& /dev/null && [[ -n ${JENV_ROOT} ]]; then
  echo -n ", jenv"
  eval "$(jenv init -)"
fi

# Show private key(s) held by ssh-agent
# ssh-add -l >& /dev/null
# RESULT=$?
# if [ ${RESULT} -eq 0 ]; then
#   echo; echo "Keys held by ssh-agent:"
#   ssh-add -l
# fi

echo

