#!/usr/bin/env bash
# vim: set noet syn=bash ft=sh ff=unix fenc=utf-8 ts=2 sw=0 : # GPP default modeline for bash script
# shellcheck shell=bash disable=SC1091,SC2155,SC3010,SC3021,SC3037 source=${GPP_HOME}
#
# Jedid
# Detects macOS auto appearance change and set some CLI applications' color setting.
# For systems other than macOS, get daytime information from webservice.

# Part of GPP

# AUTHOR: hmr
# ORIGIN: 2024-03-29

declare -g DEBUG MODE NEXTCHECK SUNRISE SUNSET NOW

DEBUG=1
SYSLOG=1

# Debug echo
function decho () {
	local PREFIX
	if (( ! SYSLOG )); then
		PREFIX="[$(date +'%Y-%m-%d %H:%M:%S')]"
	fi
	if (( DEBUG > 0 )); then
		echo "${PREFIX} $*" >&2
	fi
}

# Get sunrise and sunset time by web services
function getdaytime () {
	decho "Entering function ${FUNCNAME[0]} on pid#${BASHPID}..."

	local JSON=$(curl -s "https://api.sunrise-sunset.org/json?$(curl -s 'https://ipinfo.io/json' | jq -r ".loc" | gsed -e "s/\([0-9\.]\+\),\([0-9\.]\+\)/lat=\1\&lng=\2/g")&date=today&tzid=$(curl -s "https://ipinfo.io/json" | jq -r ".timezone")")

	NEXTCHECK=$(date -d 'tomorrow 00:00:00' +%s)
	SUNRISE=$(date -d "$(echo "${JSON}" | jq -r '.results.sunrise')" +%s)
	SUNSET=$(date -d "$(echo "${JSON}" | jq -r '.results.sunset')" +%s)
	decho "[New] NEXTCHECK=${NEXTCHECK} SUNRISE=${SUNRISE} SUNSET=${SUNSET}"
}

function check_sidechange() {
	decho "Entering function ${FUNCNAME[0]} on pid#${BASHPID}..."

	case "${OSTYPE}" in
		# macOS
		darwin* )
			decho "darwin detected."
			if defaults read -g AppleInterfaceStyle 2>&1 | grep -qi "dark" >& /dev/null; then
				# Dark side
				decho "System theme is dark mode."
				if [[ ${MODE} != "dark" ]]; then
					# Light -> Dark
					decho "Changed to dark side!"
					echo "1"
					return
				fi
			else
				# Light side
				decho "System theme is light mode."
				if [[ ${MODE} != "light" ]]; then
					# Dark -> Light
					decho "Changed to light side!"
					echo "2"
					return
				fi
			fi
			;;

		# Other Unix-like system
		* )
			decho "other unix system detected."
			decho "NOW=${NOW} NEXTCHECK=${NEXTCHECK} SUNRISE=${SUNRISE} SUNSET=${SUNSET}"
			if [[ ${NOW} -ge ${SUNRISE} && ${NOW} -le ${SUNSET} ]]; then
				# Light side
				decho "System theme is light mode."
				if [[ ${MODE} != "light" ]]; then
					# Dark -> Light
					decho "Changed to light side!"
					echo "2"
					return
				fi
			else
				# Dark side
				decho "System theme is dark mode."
				if [[ ${MODE} != "dark" ]]; then
					# Light -> Dark
					decho "Changed to dark side!"
					echo "1"
					return
				fi
			fi
			;;
	esac

	# side not changed
	decho "Side isn't changed."
	echo "0"
	return
}

function main() {
	decho "Entering function ${FUNCNAME[0]} on pid#${BASHPID}..."

	while true; do
		decho "MODE is ${MODE:-NOT SET}."

		# Get daytime info if the system isn't macOS
		if [[ ! ${OSTYPE} =~ darwin ]]; then
			NOW=$(date +%s)
			decho "Remaining time to update daytime info: $((NEXTCHECK - NOW)) secs"
			[[ -z ${NEXTCHECK} || ${NOW} -gt ${NEXTCHECK} ]] && getdaytime
		fi

		case "$(check_sidechange)" in

			# Side not changed: nothing to do
			0 )
				decho "Nothing to do."
				;;

			# Light -> Dark
			1 )
				## lsd
				decho "Setting lsd dark..."
				CONFIG_DIR="${XDG_CONFIG_HOME}/lsd"
				if [[ -d ${CONFIG_DIR} ]] && cd "${CONFIG_DIR}"; then
					ln -sf themes/default.yaml colors.yaml
				fi

				## bat
				decho "Setting bat dark..."
				CONFIG_DIR="${XDG_CONFIG_HOME}/bat"
				if [[ -d ${CONFIG_DIR} ]]  && cd "${CONFIG_DIR}"; then
					ln -sf config-dark config
				fi

				## man
				decho "Setting man dark..."
				CONFIG_DIR="${XDG_CONFIG_HOME}/man"
				if [[ -d ${CONFIG_DIR} ]]  && cd "${CONFIG_DIR}"; then
					ln -sf man.conf.dark man.conf
				fi

				# set mode
				MODE="dark"
				;;

			# Dark -> Light
			2 )
				## lsd
				decho "Setting lsd light..."
				CONFIG_DIR="${XDG_CONFIG_HOME}/lsd"
				if [[ -d ${CONFIG_DIR} ]] && cd "${CONFIG_DIR}"; then
					ln -sf themes/default-light.yaml colors.yaml
				fi

				## bat
				decho "Setting bat light..."
				CONFIG_DIR="${XDG_CONFIG_HOME}/bat"
				if [[ -d ${CONFIG_DIR} ]] && cd "${CONFIG_DIR}"; then
					ln -sf config-light config
				fi

				## man
				decho "Setting man light..."
				CONFIG_DIR="${XDG_CONFIG_HOME}/man"
				if [[ -d ${CONFIG_DIR} ]]  && cd "${CONFIG_DIR}"; then
					ln -sf man.conf.light man.conf
				fi

				# set mode
				MODE="light"
				;;
		esac

		# stop working
		sleep 15
	done
}

decho "------------------------------------------------------------"
decho "Starting Jedid on pid#${BASHPID}..."

function trap_exit() {
	decho "Quitting..."
}
trap trap_exit SIGINT

if [[ -z ${XDG_CONFIG_HOME} ]]; then
	decho "Warning: XDG_CONFIG_HOME isn't set. Setting now..."
	XDG_CONFIG_HOME="${HOME}/.config"
fi
decho "XDG_CONFIG_HOME=${XDG_CONFIG_HOME}"
decho "PATH=${PATH}"
main

