#!/usr/bin/env zsh

# vim: set et syn=bash ft=sh ff=unix fenc=utf-8 ts=4 sts=4 sw=4 : # GPP default modeline for shell script
# shellcheck shell=bash disable=SC1091

# Part of GPP

# launch_tmux
#   Launch Tmux on local or via ssh connection.
# ORIGIN: 2020-12-18 by hmr

#set -o errexit

DRY_RUN=0

# GPP_HOME="${GPP_HOME:=${HOME}/gpprofiles}"

# Determine TERM
if [[ -n $TERM_PROGRAM ]]; then
    case $TERM_PROGRAM in
        "ghostty" )
            TERM="xterm-ghostty";;
        "rio"     )
            TERM="xterm-rio";;
        "iTerm.app" )
            TERM="xterm-256color-iTerm" ;;
        "WezTerm" | "Tabby" | "WarpTerminal" | "Hyper" | "waveterm" )
            TERM="xterm-256color";;
    esac
elif [[ -n $KITTY_PID ]]; then
    TERM="xterm-kitty"
elif [[ -n $ALACRITTY_SOCKET ]]; then
    TERM="alacritty"
elif [[ $TERMINAL_NAME == "contour" ]]; then
    TERM="contour"
elif [[ -n $electermHost ]]; then
    TERM="xterm-256color"
else
    TERM="xterm-256color"
fi

TERM=${TERM_OVERRIDE:-${TERM}}

PATH=/usr/local/bin:/usr/local/sbin:${PATH}
SSH_BIN=$(which ssh)
declare -a SSH_OPT=("-t")

MODE="auto"
TMUX_BIN="${TMUX_BIN_OVERRIDE:-"tmux"}"
# TMUX_BIN="/Users/hmr/src/tmux/tmux-kkp/tmux"

if [[ ${#TMUX_OPT_OVERRIDE[@]} -eq 0 ]]; then
    TMUX_OPT=("-l")
else
    TMUX_OPT=("${TMUX_OPT_OVERRIDE[@]}")
fi
# TMUX_OPT=("-l" "-vv") # tmux debug setting

TMUX_CMD="${TMUX_CMD_OVERRIDE}"

post_processing() {
    # Logout setting
    if [[ -r "${ZDOTDIR}/dot-zlogout" ]]; then
        source "${ZDOTDIR}/dot-zlogout"
    fi
}

show_usage() {
    echo "Usage:"
    echo "launch_tmux login_info [command]"
    echo "  login_info is ssh style like 'user@server'"
    echo "  command is 'auto'(default), 'new' or 'reattach'."
    echo
}

generate_sesid() {
    TMP_SESID=""

    echo "Making session id... "

    if [[ -r /dev/urandom ]]; then
        # urandom available
        echo "by /dev/urandom"
        TMP_SESID=$(dd bs=64 count=1 if=/dev/urandom 2>/dev/null | shasum -b | cut -c1-6)
    else
        # urandom not available -> use epoch second
        echo "by epoch"
        TMP_SESID=$(dc -e "16o 10i $(date +%s)p" | shasum | cut -c1-6)
    fi

    echo "${TMP_SESID}"
}

trap 'post_processing' 1 2 3 15

# ==================== ENTRY POINT ====================
echo
echo "Starting $0..."
echo "TERM=${TERM}"
echo "SHELL=${SHELL}"
echo "BASH=${BASH}"
echo "GPP_HOME=${GPP_HOME}"
echo "PATH=${PATH}"

if [[ -z ${GPP_HOME} ]]; then
    echo "\$GPP_HOME isn't set."
    exit 1
fi

source "${GPP_HOME}/settings/apps/shell_common/dot-shell_shellenv"

# Ssh-agent setting
# Derived from gpp's dot-profile_ssh-agent
ZDOTDIR="${HOME}/.config/zsh"
if [[ -r "${ZDOTDIR}/dot-zprofile_ssh-agent" ]]; then

    echo "Calling dot-(z)profile_ssh-agent..."
    echo "--------------------------------------------------------------------------------"
    source "${ZDOTDIR}/dot-zprofile_ssh-agent"
    echo "--------------------------------------------------------------------------------"
    SSH_OPT+=("-A")
fi

# Check number of args
if (( $# == 0 )); then
    echo "Error: Not enough arguments"
    show_usage
    exit 1
fi

# Set SSH target host
TRGT_HOST=$1
shift

# Handling other arguments
CMD_OPT=""
while (( $# > 0 ))
do
    OPT=$1
    shift
    case "${OPT}" in
        "auto" )
            MODE=${OPT}
            ;;

        "new" )
            MODE=${OPT}
            ;;

        "reattach" )
            MODE=${OPT}
            ;;

        "dryrun" )
            DRY_RUN="1"
            echo "Dry-run mode"
            ;;

        "debug" )
            TMUX_OPT+=(-v)
            echo "Debug mode. Log file like 'tmux-{server|client}-yyyyy.log' will be generated."
            SSH_OPT+=("-v")
            ;;

        tmux=* )
            TMUX_BIN="${OPT#*=}"
            echo "Use ${TMUX_BIN} as tmux."
            ;;

		term=* )
			TERM="${OPT#*=}"
			echo "TERM was overridden by '${TERM}'."
			;;

        *)
            CMD_OPT="${CMD_OPT} ${OPT}"
            ;;
    esac
done



# Check SSH Agent
if (( ${SSH_AGENT_PID:-0} == 0 )); then
    echo "SSH Agent isn't configured."
    #exit 1
fi


# Check SSH Connectivity
# if [ "${TRGT_HOST}" != "localhost" ]; then
#   TMP_SSH_LOG=$("${SSH_BIN}" -o PasswordAuthentication=no "${TRGT_HOST}" 2>&1)
#   echo "${TMP_SSH_LOG}"
#   if [[ ${TMP_SSH_LOG} =~ "WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!" ]]; then
#     echo "SSH error occured."
#     echo "--------------------"
#     echo "${TMP_SSH_LOG}"
#     echo "--------------------"
#     exit 2
#   fi
# fi

# Tmux's Session ID processing("reattach" or "auto" mode only)
if [[ $MODE == reattach || $MODE == auto ]]; then
    echo "MODE: ${MODE}"
    # Get the Tmux session ID from already existing session.
    # local
    if [[ $TRGT_HOST == localhost ]]; then
        # Local
        echo "SESID=\$(${TMUX_BIN} ls 2>&1 | sort -n -r -k 2 | head -n 1 | cut -c1-6 | tr -d \"\\\n\")"
        SESID=$(${TMUX_BIN} ls 2>&1 | sort -n -r -k 2 | head -n 1 | cut -c1-6 | tr -d "\n")
    else
        # Remote
        echo "SESID=\$(${SSH_BIN} ${SSH_OPT[*]} \"${TRGT_HOST}\" \"${TMUX_BIN}\" ls 2> /dev/null | sort -n -r -k 2 | head -n 1)"
        SESID=$("${SSH_BIN}" "${SSH_OPT[@]}" "${TRGT_HOST}" "${TMUX_BIN}" ls 2> /dev/null | sort -n -r -k 2 | head -n 1)
		echo "SESID='${SESID}'"
    fi

    # Error check
    case "${SESID}" in
        "server exited unexpectedly" )
            echo "It looks some kind of error happens on the server."
            exit 1
            ;;
        bash:* | zsh:* ) # bash: line 1: tmux: command not found
            echo "Tmux hasn't been installed into the target host."
            exit 1
            ;;
		"missing or unsuitable terminal:"* )
			echo "TERM='${TERM}' isn't exist on target host."
			exit 1
			;;
        * )
            echo "Error check passed."
            ;;
    esac

    if echo "${SESID}" | ggrep -Pq "[^:]+?: \d+ "; then
        SESID=$(echo "${SESID}" | cut -d ":" -f 1)
    else
        SESID=$(echo "${SESID}" | cut -c 1-6)
    fi

    echo "SESID='${SESID}'"
    case "${SESID}" in
        # Failed to get already existing session id.
        "no ser"* | "no cur"* | "error "* | "server"* | "" )
            # Session ID generation
            # SESID=$(generate_sesid)
            # CMD_OPT="${CMD_OPT} -s ${SESID}"

            if [[ $MODE == auto ]]; then
                TMUX_CMD="new-session"
            else
                # "reattach" mode
                echo "Error: The session to reattach not found."
                exit 1
            fi
            ;;

        * )
            TMUX_CMD="attach-session"
            if [[ $TRGT_HOST == localhost ]]; then
                CMD_OPT="${CMD_OPT} -t ${SESID}"
            else
                CMD_OPT="${CMD_OPT} -t '=${SESID}'"
            fi
    esac
elif [[ $MODE == new ]]; then
    TMUX_CMD="new-session"
else
    echo "Error: Failed to determine mode. Choose 'auto' 'new' 'reattach'"
fi

# Connect to local or remote host and launch tmux
case ${TRGT_HOST} in
    localhost )
        echo "${TMUX_BIN} ${TMUX_OPT[*]} ${TMUX_CMD} ${CMD_OPT}"
        (( DRY_RUN == 0 )) &&
            "${TMUX_BIN}" "${TMUX_OPT[@]}" "${TMUX_CMD}"
        ;;

    * )
        echo "${SSH_BIN} ${SSH_OPT[*]} ${TRGT_HOST} ${TMUX_BIN} ${TMUX_OPT[*]} ${TMUX_CMD} ${CMD_OPT:-}"
        (( DRY_RUN == 0 )) &&
            "${SSH_BIN}" "${SSH_OPT[@]}" "${TRGT_HOST}" "${TMUX_BIN}" "${TMUX_OPT[@]}" "${TMUX_CMD}" "${CMD_OPT:-}"
        ;;
esac
