## name: Gruvbox Dark (gpprofiles)
## author: Hatchi Maru
## license: MIT/X11
## upstream: https://raw.githubusercontent.com/gruvbox-community/gruvbox-contrib/master/kitty/gruvbox-dark.conf

selection_foreground    #e8dbb6
selection_background    #645c54

background              #272727
foreground              #e8dbb6

color0                  #272727
color1                  #bb3629
color2                  #979736
color3                  #cd9b3e
color4                  #548386
color5                  #a66584
color6                  #739b6e
color7                  #a59986
color8                  #8f8375
color9                  #e75740
color10                 #b8ba46
color11                 #f0bf4f
color12                 #89a498
color13                 #c8899a
color14                 #98be82
color15                 #e8dbb6

cursor                  #e8dbb6
cursor_text_color       #272727

url_color               #c7642a
