## name: Gruvbox Light (gpprofiles)
## author: Hatchi Maru
## license: MIT/X11
## upstream: https://raw.githubusercontent.com/gruvbox-community/gruvbox-contrib/master/kitty/gruvbox-light.conf

selection_foreground    #645c54
selection_background    #d2c4a4

background              #f9f1cb
foreground              #272727

color0                  #f9f1cb
color1                  #8f1b14
color2                  #787426
color3                  #ab782e
color4                  #2c6475
color5                  #85436e
color6                  #4f795a
color7                  #3b3836
color8                  #988376
color9                  #bb3629
color10                 #979736
color11                 #cd9b3e
color12                 #548386
color13                 #a66584
color14                 #739b6d
color15                 #796f65

cursor                  #272727
cursor_text_color       #f9f1cb

url_color               #a1421b
