; base16 theme for Fast-Syntax-Highlighting
; For Light environment
; Part of GPP

[base]
default          = none
unknown-token    = 1,bold
commandseparator = none
redirection      = 200
here-string-tri  = 14
here-string-text = 5,bold
here-string-var  = 1,bold
comment          = 8
; e.g.) "FD" in `exec {FD}>file`
exec-descriptor  = 9,bold
; e.g.) "master" in `git co master` if master branch exists.
correct-subtle   = 12
; e.g.) "not_exist" in `git co not_exist` if not_exist branch does not exist.
incorrect-subtle = 1
; Only used with ssh:  "@" in `ssh user@host`
subtle-separator = 1
; Only used with awk and subversion
subtle-bg        = bg:252
secondary        = XDG:base16-t1
recursive-base   =

[command-point]
; if, then, elif, else, fi, for, foreach, while, until, repeat, do, done,
; case, esac, select, time, coproc, !, {, }, function, end, typeset, declare,
; local, integer, float, export, readonly, always(try-always construct)
; '[[' and ']]' is 'double-sq-bracket'
reserved-word  = 13
; A subcommand within a command. e.g. The “status” part of `git status`.
subcommand     = 14
alias          = 12
; zsh's suffix alias, e.g. `alias -s txt=vim`
suffix-alias   = 12
; zsh's global alias, e.g. `alias -g G='| grep'`
global-alias   = 4,bg:11
; Shell builtin commands
builtin        = 8
; Defined functions
function       = 65
; Commands found in PATH
command        = 12

; builtin, command, exec, noglob, sudo. orig=14
precommand     = 177
hashed-command = 12
single-sq-bracket = 12
double-sq-bracket = 12
double-paren   = 13

[paths]
path          = none
pathseparator = none
path-to-dir   = none
; e.g.) *.c foo? [abc]* **/*.c
globbing      = 14
globbing-ext  = 14

[brackets]
paired-bracket = bg:8
bracket-level-1 = 7
bracket-level-2 = 5
bracket-level-3 = 4

[arguments]
; e.g.) <command> -a
single-hyphen-option   = 11
; e.g.) <command> --arg
double-hyphen-option   = 11
; e.g.) <command> `back-quoted-argument`
back-quoted-argument   = none
; e.g.) <command> 'single-quoted-argument'
single-quoted-argument = 10
; e.g.) <command> "double-quoted-argument"
double-quoted-argument = 10
; e.g.) <command> $'dollar-quoted-argument'
dollar-quoted-argument = 10
; e.g.) The "VAL" part of `<command> --arg=VAL(string)`
optarg-string          = 11
; e.g.) The "NUM" part of `<command> --arg=NUM(number)`
optarg-number          = 11

[in-string]
; escaped strings in $'...' e.g. <command> $'foo\nbar\\\g'
back-dollar-quoted-argument           = 6
; backslash or $... in "..." e.g. <command> "foo\n$VAR\"quoted\""
back-or-dollar-double-quoted-argument = 1

[other]
variable             = 33
assign               = none
assign-array-bracket = 5
; e.g.) !!, !$, !foo, !-2, !?foo?
history-expansion    = 6,bold

[math]
; e.g.) ((VAR+1)); echo $((VAR+1))
mathvar = 1
mathnum = 9
matherr = 1,bold

[for-loop]
; e.g.) for (( i = 10; i < 20; ++i ))
; "i": forvar, "10/20": fornum, "<": foroper, ";": forsep
forvar = 1
fornum = 9
foroper = none
forsep = none

[case]
case-input       = 1
case-parentheses = 5
case-condition   = bg:252
